### ISSUE TITLE
Bundled resource not usable

### ISSUE THREAD

**Issue by Zmnortal** [xapijs/cmi5-demo#113]
Hi, I downloaded 1.3.2 demo.zip and try to launched on local. Unfortunately, I encountered the following error.

<img width="1221" alt="image" src="https://github.com/user-attachments/assets/bedfcf2b-c0fd-4912-ba5f-6fb03bd72931">

I use Live Server in VSCode as server.

**Comment by CookieCookson** [comment]
Hi @Zmnortal the CMI5 demo requires the query string to be correctly populated with the required CMI5 parameters in order to work.

You can either upload the demo to a compliant CMI5 environment e.g. Scorm Cloud or provide your own query params for your environment.

**Comment by Zmnortal** [comment]
Thank @CookieCookson for the information. I appreciate your guidance.

As I'm new to CMI5, I'll take the time to explore and understand how to properly set up the demo with the necessary query parameters.

**Comment by CookieCookson** [comment]
@Zmnortal No problem, I hope you find everything you need.
